# Site wide configuration

title: iHomeAutomate
description: Tips and information about home automation - Tutorials, experiences, applications that make home automation easier
logo: # 120x120 px default image used for Twitter summary card
teaser: home-400x250.png # 400x250 px default teaser image used in image archive grid
locale:
url: https://www.ihomeautomate.com
#url: http://localhost:4000

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: iHomeAutomate
  web: https://iHomeAutomate.com
  github: ihomeautomate
  email:
  twitter: ihomeautomate
  facebook: pages/iHomeAutomate/218034961586842
  google:
    plus: +iHomeAutomateEU
    ad-client: ca-pub-8912601207925232
    ad-slot: 5196264642
  bio:
  avatar: bio-photo.jpg # 160x160 px image for author byline
disqus-shortname: iHomeAutomate


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
